# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "kotlin*"
      androidx:
        patterns:
          - "androidx*"
          - "com.google.android.material*"
      testing:
        patterns:
          - "junit*"
          - "org.junit*"
          - "org.mockito*"
          - "io.mockk*"

  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "kotlin*"
      androidx:
        patterns:
          - "androidx*"
          - "com.google.android.material*"
      testing:
        patterns:
          - "junit*"
          - "org.junit*"
          - "org.mockito*"
          - "io.mockk*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
