# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Madrid"
    groups:
      everything:
        applies-to: version-updates
        patterns: ["*"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  # Gradle (app module)
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Madrid"
    groups:
      everything:
        applies-to: version-updates
        patterns: ["*"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
      timezone: "Europe/Madrid"
    groups:
      everything:
        applies-to: version-updates
        patterns: ["*"]
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
